on: 
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'printing folder contets before'
        run: ls

      - uses: actions/checkout@v3
       

      - name: 'printing folder contets after'
        run: ls  

